# Generated by Django 3.2.9 on 2022-11-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EgModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_field', models.CharField(max_length=100)),
                ('textarea', models.TextField()),
                ('integer', models.IntegerField()),
                ('floating_number', models.FloatField()),
                ('date_filed', models.DateField()),
                ('image_filed', models.ImageField(upload_to='images')),
            ],
        ),
    ]
