# Generated by Django 3.2.9 on 2022-11-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog_blognumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='percent',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
