# Generated by Django 3.2.9 on 2022-11-04 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blog_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='percent',
            new_name='price',
        ),
    ]
